import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import obsidianmd from "eslint-plugin-obsidianmd";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig(
	globalIgnores([
		"node_modules/**",
		"main.js",
		"esbuild.config.mjs",
		"versions.json",
		"bun.lock",
		"crates/**",
		"_archive/**",
		"_setup/**",
		// generated by `bun run wasm`, never hand-edited (see AGENTS.md)
		"wasm/**",
	]),
	js.configs.recommended,
	tseslint.configs.recommended,
	obsidianmd.configs.recommended,
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node,
			},
			parserOptions: {
				projectService: {
					allowDefaultProject: ["*.mts"],
				},
				tsconfigRootDir: import.meta.dirname,
			},
		},
	},
	{
		// Test doubles and mocks intentionally use loosely typed stand-ins for
		// Obsidian APIs and WASM handles; this code is never shipped.
		files: ["src/__tests__/**/*.ts", "src/__mocks__/**/*.ts"],
		rules: {
			// vitest runs in node: there is no window to prefer, and probing
			// globalThis is how a test removes a platform API (DecompressionStream)
			// to exercise the fallback path.
			"obsidianmd/no-global-this": "off",
			"@typescript-eslint/no-explicit-any": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/unbound-method": "off",
		},
	},
);
